"""
Multilingual bot texts.
Usage:  from bot.texts import t
        t('uz', 'welcome', name="Ali")
"""

_T = {
    'uz': {
        'choose_lang':   "Tilni tanlang 🌐\n\nDavom etish uchun quyidagi tillardan birini tanlang:",
        'send_phone':    "📱 Salom, <b>{name}</b>! 👋\n\n<b>Tartibly</b>ga xush kelibsiz.\nDavom etish uchun telefon raqamingizni yuboring:",
        'phone_btn':     "📞 Telefon raqamni yuborish",
        'phone_saved':   "✅ Ro'yxatdan o'tdingiz!\n\n<b>Tartibly</b>ga xush kelibsiz 🎉\nXizmatni tanlang va qulay navbat oling!",
        'welcome':       "<b>Tartibly</b>ga xush kelibsiz, <b>{name}</b>! 👋\n\nQuyidagi menyudan foydalaning:",
        'btn_biz':       "Bizneslar 🏢",
        'btn_tickets':   "Navbatlarim 📋",
        'no_businesses': "😔 Hozircha bizneslar yo'q.",
        'choose_biz':    "🏢 Biznesni tanlang:",
        'no_branches':   "😔 Bu biznesda faol filiallar yo'q.",
        'choose_branch': "🏪 Filialni tanlang:",
        'no_services':   "😔 Bu filialda faol xizmatlar yo'q.",
        'choose_svc':    "💼 Xizmatni tanlang:",
        'svc_info':      "<b>{title}</b>\n📍 {branch}\n⏱ ~{time} daqiqa\n💰 {price}\n🎫 Navbatda: {waiting} kishi",
        'price_free':    "Bepul",
        'no_tickets':    "😔 Sizda hozircha faol chipta yo'q.\n\n«Bizneslar» bo'limidan navbat oling.",
        'tickets_hdr':   "🎫 <b>Faol chiptalarim:</b>\n\n",
        'ticket_row':    "🎫 <code>{num}</code> — {svc}\n📍 {branch}\n📊 <b>{status}</b>{pos}\n",
        'ticket_pos':    " | Navbat: {n}-o'rin",
        'ticket_taken':  "✅ <b>Chipta olindi!</b>\n\n🎫 Raqam: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n👥 Navbat o'rni: <b>{pos}-o'rin</b>\n⏱ Taxminiy kutish: <b>~{wait} daq</b>",
        'already_ticket':"⚠️ Sizda allaqachon <code>{num}</code> raqamli chipta bor.\nNavbat o'rni: {pos}",
        'confirm_take':  "✅ Ha, navbat olish",
        'cancel':        "❌ Bekor qilish",
        'back':          "🔙 Orqaga",
        'confirm_book':  "✅ Yozilish",
        'cancelled':     "Bekor qilindi.",
        'need_register': "Veb-saytda ro'yxatdan o'tish talab etiladi.",
        'need_phone':    "Avval telefon raqamingizni yuboring (/start).",
        'notify_3':      "⏰ <b>Diqqat!</b>\n\n🎫 Chipta: <code>{num}</code>\n💼 {svc} — {branch}\n\nSizdan oldin faqat <b>3 kishi</b> qoldi!\nIltimos, tayyor bo'ling. 🏃",
        'notify_1':      "⚡ <b>Deyarli navbatingiz!</b>\n\n🎫 Chipta: <code>{num}</code>\n💼 {svc} — {branch}\n\nSizdan oldin faqat <b>1 kishi</b> qoldi!\nHoziroq tayyor bo'ling! 🏃‍♂️",
        'notify_called': "🔔 <b>Navbatingiz keldi!</b>\n\n🎫 Chipta: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nIltimos, <b>darhol</b> operatorga yaqinlashing!",
        'notify_skipped':"↷ <b>Chipta o'tkazib yuborildi</b>\n\n🎫 Chipta: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nAfsuski, navbatingiz o'tkazib yuborildi.\nQayta navbat olish uchun biznesga kiring.",
        'notify_done':   "✅ <b>Xizmat yakunlandi!</b>\n\n🎫 Chipta: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nXizmatimizdan foydalanganingiz uchun rahmat! 🙏\nXizmatni baholash uchun saytga kiring.",
    },
    'ru': {
        'choose_lang':   "Выберите язык 🌐\n\nДля продолжения выберите язык:",
        'send_phone':    "📱 Привет, <b>{name}</b>! 👋\n\nДобро пожаловать в <b>Tartibly</b>.\nОтправьте ваш номер телефона для продолжения:",
        'phone_btn':     "📞 Отправить номер телефона",
        'phone_saved':   "✅ Регистрация успешна!\n\nДобро пожаловать в <b>Tartibly</b> 🎉\nВыберите услугу и займите очередь!",
        'welcome':       "Добро пожаловать, <b>{name}</b>! 👋\n\nВоспользуйтесь меню ниже:",
        'btn_biz':       "Бизнесы 🏢",
        'btn_tickets':   "Мои талоны 📋",
        'no_businesses': "😔 Пока нет бизнесов.",
        'choose_biz':    "🏢 Выберите бизнес:",
        'no_branches':   "😔 В этом бизнесе нет активных филиалов.",
        'choose_branch': "🏪 Выберите филиал:",
        'no_services':   "😔 В этом филиале нет активных услуг.",
        'choose_svc':    "💼 Выберите услугу:",
        'svc_info':      "<b>{title}</b>\n📍 {branch}\n⏱ ~{time} мин\n💰 {price}\n🎫 В очереди: {waiting} чел.",
        'price_free':    "Бесплатно",
        'no_tickets':    "😔 У вас нет активных талонов.\n\nПерейдите в «Бизнесы» чтобы занять очередь.",
        'tickets_hdr':   "🎫 <b>Мои активные талоны:</b>\n\n",
        'ticket_row':    "🎫 <code>{num}</code> — {svc}\n📍 {branch}\n📊 <b>{status}</b>{pos}\n",
        'ticket_pos':    " | Позиция: {n}",
        'ticket_taken':  "✅ <b>Талон получен!</b>\n\n🎫 Номер: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n👥 Ваша позиция: <b>{pos}</b>\n⏱ Ожидание: <b>~{wait} мин</b>",
        'already_ticket':"⚠️ У вас уже есть талон <code>{num}</code>.\nПозиция: {pos}",
        'confirm_take':  "✅ Да, взять очередь",
        'cancel':        "❌ Отмена",
        'back':          "🔙 Назад",
        'confirm_book':  "✅ Записаться",
        'cancelled':     "Отменено.",
        'need_register': "Требуется регистрация на сайте.",
        'need_phone':    "Сначала отправьте номер телефона (/start).",
        'notify_3':      "⏰ <b>Внимание!</b>\n\n🎫 Талон: <code>{num}</code>\n💼 {svc} — {branch}\n\nДо вас осталось <b>3 человека</b>!\nПожалуйста, будьте готовы. 🏃",
        'notify_1':      "⚡ <b>Почти ваша очередь!</b>\n\n🎫 Талон: <code>{num}</code>\n💼 {svc} — {branch}\n\nДо вас остался <b>1 человек</b>!\nБудьте готовы прямо сейчас! 🏃‍♂️",
        'notify_called': "🔔 <b>Ваша очередь подошла!</b>\n\n🎫 Талон: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nПодойдите к оператору <b>немедленно</b>!",
        'notify_skipped':"↷ <b>Талон пропущен</b>\n\n🎫 Талон: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nК сожалению, ваша очередь была пропущена.\nЗайдите в раздел бизнесов, чтобы взять новый талон.",
        'notify_done':   "✅ <b>Обслуживание завершено!</b>\n\n🎫 Талон: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nСпасибо, что воспользовались нашим сервисом! 🙏\nОцените услугу на сайте.",
    },
    'en': {
        'choose_lang':   "Choose language 🌐\n\nSelect your preferred language:",
        'send_phone':    "📱 Hello, <b>{name}</b>! 👋\n\nWelcome to <b>Tartibly</b>.\nShare your phone number to continue:",
        'phone_btn':     "📞 Share phone number",
        'phone_saved':   "✅ Registration complete!\n\nWelcome to <b>Tartibly</b> 🎉\nPick a service and join the queue!",
        'welcome':       "Welcome back, <b>{name}</b>! 👋\n\nUse the menu below:",
        'btn_biz':       "Businesses 🏢",
        'btn_tickets':   "My Tickets 📋",
        'no_businesses': "😔 No businesses available yet.",
        'choose_biz':    "🏢 Select a business:",
        'no_branches':   "😔 No active branches for this business.",
        'choose_branch': "🏪 Select a branch:",
        'no_services':   "😔 No active services at this branch.",
        'choose_svc':    "💼 Select a service:",
        'svc_info':      "<b>{title}</b>\n📍 {branch}\n⏱ ~{time} min\n💰 {price}\n🎫 In queue: {waiting} people",
        'price_free':    "Free",
        'no_tickets':    "😔 You have no active tickets.\n\nGo to «Businesses» to join a queue.",
        'tickets_hdr':   "🎫 <b>My active tickets:</b>\n\n",
        'ticket_row':    "🎫 <code>{num}</code> — {svc}\n📍 {branch}\n📊 <b>{status}</b>{pos}\n",
        'ticket_pos':    " | Position: {n}",
        'ticket_taken':  "✅ <b>Ticket taken!</b>\n\n🎫 Number: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n👥 Your position: <b>{pos}</b>\n⏱ Est. wait: <b>~{wait} min</b>",
        'already_ticket':"⚠️ You already have ticket <code>{num}</code>.\nPosition: {pos}",
        'confirm_take':  "✅ Yes, join queue",
        'cancel':        "❌ Cancel",
        'back':          "🔙 Back",
        'confirm_book':  "✅ Book",
        'cancelled':     "Cancelled.",
        'need_register': "Registration on the website is required.",
        'need_phone':    "Please share your phone number first (/start).",
        'notify_3':      "⏰ <b>Heads up!</b>\n\n🎫 Ticket: <code>{num}</code>\n💼 {svc} — {branch}\n\nOnly <b>3 people</b> ahead of you!\nPlease get ready. 🏃",
        'notify_1':      "⚡ <b>Almost your turn!</b>\n\n🎫 Ticket: <code>{num}</code>\n💼 {svc} — {branch}\n\nOnly <b>1 person</b> ahead of you!\nGet ready right now! 🏃‍♂️",
        'notify_called': "🔔 <b>Your turn!</b>\n\n🎫 Ticket: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nPlease approach the operator <b>immediately</b>!",
        'notify_skipped':"↷ <b>Ticket skipped</b>\n\n🎫 Ticket: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nUnfortunately your turn was skipped.\nVisit the businesses section to take a new ticket.",
        'notify_done':   "✅ <b>Service complete!</b>\n\n🎫 Ticket: <code>{num}</code>\n💼 {svc}\n📍 {branch}\n\nThank you for using our service! 🙏\nRate your experience on the website.",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    """Return localized text, falling back to 'uz'."""
    text = _T.get(lang, _T['uz']).get(key) or _T['uz'].get(key, key)
    return text.format(**kwargs) if kwargs else text
